Fix: Support emojis
marcreichel/alpine-typewriter pull request #8
Opened 2024-11-29 22:26 UTC by jonnitto

## Before

![Screenshot 2024-11-29 at 23 24 19](https://github.com/user-attachments/assets/8536ca8f-56ff-4ed7-992f-c7a5ab29976f)

## After

![Screenshot 2024-11-29 at 23 25 29](https://github.com/user-attachments/assets/f0efca20-1171-4d4d-8459-fea35418b3dd)

2025-01-06 13:40 UTC, marcreichel requested changes

2025-01-06 13:40 UTC, marcreichel commented on src/index.js
>          },
Nice fix! Thanks!

Please only revert those indentations here.

2025-01-06 21:42 UTC, jonnitto commented on src/index.js
>          },
Done

2025-01-22 17:01 UTC, marcreichel approved these changes

2025-01-22 17:02 UTC, merged